---
abstract: 'Olfactory Receptor family Assigner (ORA)'
author:
  - 'Michael Bekaert <michael.bekaert@stir.ac.uk>'
build_requires: {}
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ora
provides:
  Bio::ORA:
    file: lib/Bio/ORA.pm
    version: v1.9.1
requires:
  Bio::Root::Version: 0
  Cwd: 0
  Getopt::Long: 0
  IO::File: 0
  perl: v5.6.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: v1.9.1
